import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import AdmZip from 'adm-zip';
import { convertAbletonUpload } from '../src/services/projectConvert/ConvertService.js';
const out = fs.mkdtempSync(path.join(os.tmpdir(), 'conv-'));
const zip = new AdmZip(process.argv[2]);
console.log('zip entries with .als:');
for (const e of zip.getEntries()) if (/\.als$/i.test(e.entryName)) console.log(`  ${e.entryName} (${e.header.size} bytes)`);
const meta = convertAbletonUpload(process.argv[2], path.basename(process.argv[2]), 'u', out, []);
console.log('\nsource:', meta.report.source, '| tracks', meta.report.stats.tracks);
console.log('plugins:', meta.report.plugins.join(', ') || '(none)');
console.log('libraries:', meta.report.libraries.map((l) => `${l.plugin}@${l.track}`).join(', ') || '(none)');
